FROM ubuntu:18.04

COPY ./setupdhcp.sh /opt/setupdhcp.sh

# net-tools --> ifconfig
# iputils-ping --> ping
# ifupdown --> ifup, ifdown, /etc/network/interfaces ...

RUN apt-get update \
    && apt-get install -y vim \
    && apt-get install -y net-tools \
    && apt-get install -y iputils-ping \
    && apt-get install -y ifupdown

RUN chmod +x /opt/setupdhcp.sh

# Ejecutar este script al iniciar el contenedor
ENTRYPOINT [ "/opt/setupdhcp.sh" ]